name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7
        with:
          go-version: 1.22.2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@5742e2a039330cbb23ebf35f046f814d4c6ff811
        with:
          args: release --clean
        env:
          GITHUB_TOKEN = ${{ secrets.GITHUB_TOKEN  }}

      - name: Add attestations
        uses: actions/attest-build-provenance@951c0c5f8e375ad4efad33405ab77f7ded2358e4
        with:
          subject-path: "./dist/jtac_*/jtac"
